plugin:
  install: 
    language: bash
    install_script: install.sh
    dependencies:
      - kubectl

  deployment:
    language: bash
    deployment_script: deploy.sh
    core_schema_parsing: false
    before_hook_scripts: false
    after_hook_scripts: false
